name: Main workflow

on:
  pull_request:
  push:
  schedule:
    # Prime the caches every Monday
    - cron: 0 1 * * MON

permissions: read-all
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        ocaml-compiler:
          - "5.0"

    runs-on: ubuntu-latest

    steps:
      - name: Checkout tree
        uses: actions/checkout@v3
        
      - name: Set-up OCaml 4.14
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: 4.14
          dune-cache: true

      - name: Lint opam
        uses: ocaml/setup-ocaml/lint-opam@v2
      
      - run: opam init
      
      - run: opam switch create 4.14.1 4.14.1
      
      - run: opam switch 4.14.1
      
      - run: eval $(opam env)
      
      - run: opam remote add grew "http://opam.grew.fr"
      
      - run: opam update
      
      - run: opam install grew
      
      - run: opam install grewpy_backend
      
      - run: opam exec -- dune build

      - run: opam exec -- dune runtest
      
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install grewpy_backend
        run: pip3 install grewpy --upgrade
      


